export type ShortcutDefinition = readonly [string, string, ...string[]];

export const shortcutDefinitions: ShortcutDefinition[] = [
  ["New chat", "Start a new chat", "⌘N", "⇧⌘O"],
  ["Temporary chat", "Start a chat that won't appear in history", "⇧⌘N"],
  ["Quick chat", "Start a lightweight chat in the quick composer", "⌥⌘N"],
  ["Archive chat", "Archive the current chat", "⇧⌘A"],
  ["New standalone chat", "Start a new chat outside of any project", "⌥⌘O"],
  ["Open side chat", "Open the current chat in a side chat", "⌥⌘S"],
  ["Open in new window", "Open the current chat in a new window", "Unassigned"],
  ["Toggle pin", "Pin or unpin the current chat", "⌥⌘P"],
  ["Focus browser address bar", "Focus the in-app browser address bar", "⌘L"],
  ["Go to line", "Go to a line in the current file", "⌘L"],
  ["Back", "Go back in navigation history", "⌘[", "Mouse Back"],
  ["Forward", "Go forward in navigation history", "⌘]", "Mouse Forward"],
  [
    "Next recently viewed chat",
    "Cycle to the next recently viewed chat",
    "⌃Tab",
  ],
  ["Next tab", "Switch to the next tab", "⌃Tab", "⇧⌘]", "⌥⌘Right"],
  ["Next chat", "Switch to the next chat", "⇧⌘]", "⌥⌘Right"],
  [
    "Previous recently viewed chat",
    "Cycle to the previous recently viewed chat",
    "⌃⇧Tab",
  ],
  ["Previous tab", "Switch to the previous tab", "⌃⇧Tab", "⇧⌘[", "⌥⌘Left"],
  ["Previous chat", "Switch to the previous chat", "⇧⌘[", "⌥⌘Left"],
  ["Switch chat…", "Search and switch to a chat", "Unassigned"],
  ["Switch to Chat", "Switch to Chat", "⌃1"],
  ["Switch to Work", "Switch to Work", "⌃2"],
  ["Switch to Codex", "Switch to Codex", "⌃3"],
  ["Open browser tab", "Open a new browser tab", "⌘T"],
  ["Open review tab", "Open the review tab", "⌃⇧G"],
  ["Toggle bottom panel", "Show or hide the bottom panel", "⌘J"],
  ["Toggle browser panel", "Show or hide the browser panel", "⇧⌘B"],
  ["Toggle pinned summary", "Show or hide the pinned summary", "Unassigned"],
  [
    "Toggle review",
    "Show or hide Review for the current Git-backed chat",
    "Unassigned",
  ],
  ["Toggle sidebar", "Show or hide the sidebar", "⌘B"],
  ["Toggle Review panel", "Show or hide Review for the current chat", "⌥⌘B"],
  ["Open terminal", "Open the terminal panel", "⌃`"],
  [
    "Environment action 1",
    "Run the environment action in this shortcut slot",
    "⇧⌘D",
  ],
  [
    "Environment action 2",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  [
    "Environment action 3",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  [
    "Environment action 4",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  [
    "Environment action 5",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  [
    "Environment action 6",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  [
    "Environment action 7",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  [
    "Environment action 8",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  [
    "Environment action 9",
    "Run the environment action in this shortcut slot",
    "Unassigned",
  ],
  ["Commit or push", "Open commit or push options", "Unassigned"],
  ["Create branch", "Open branch creation options", "Unassigned"],
  ["Create draft PR", "Open draft pull request creation options", "Unassigned"],
  ["Create PR", "Open pull request creation options", "Unassigned"],
  ["Merge PR", "Open pull request merge options", "Unassigned"],
  [
    "Open PR on GitHub",
    "Open the pull request linked to the current chat",
    "Unassigned",
  ],
  ["Open folder", "Add a local project to ChatGPT", "⌘O"],
  [
    "Force reload skills",
    "Refresh the skill catalog for the current context",
    "Unassigned",
  ],
  ["Go to skills", "Browse installed and recommended skills", "Unassigned"],
  ["Import from other AI apps", "Import from other AI apps", "Unassigned"],
  ["Keyboard shortcuts", "Customize keyboard shortcuts", "Unassigned"],
  ["MCP", "Configure MCP servers", "Unassigned"],
  ["Personality", "Adjust tone and response style", "Unassigned"],
  [
    "Clear all unreads",
    "Mark all chats and scheduled task updates as read",
    "⇧Escape",
  ],
  ["Feedback", "Send product feedback to the ChatGPT team", "Unassigned"],
  ["Log out", "Sign out of ChatGPT", "Unassigned"],
  [
    "Manage scheduled tasks",
    "Create or manage scheduled tasks from the current page",
    "Unassigned",
  ],
  ["Show pet", "Open the pet overlay", "Unassigned"],
  ["Open control window", "Open the voice chat control window", "Unassigned"],
  ["Redo last action", "Redo the most recently undone app action", "⇧⌘Z"],
  ["Settings", "Open ChatGPT settings", "⌘,"],
  ["Undo last action", "Undo the most recent app action", "⌘Z"],
  ["Approve request", "Approve the active request", "⏎"],
  ["Decline request", "Decline the active request", "Escape"],
  ["Close Tab", "Close the active tab", "⌘W"],
  ["Close", "Close the active window", "⌘W"],
  [
    "Attach files and folders",
    "Attach files and folders to the active composer",
    "Unassigned",
  ],
  ["Add photos", "Add photos to the active composer", "Unassigned"],
  [
    "Cycle reasoning effort",
    "Cycle through composer reasoning effort options",
    "Unassigned",
  ],
  [
    "Decrease reasoning effort",
    "Decrease the current composer reasoning effort",
    "Unassigned",
  ],
  [
    "Increase reasoning effort",
    "Increase the current composer reasoning effort",
    "Unassigned",
  ],
  ["Open model picker", "Open the composer model picker", "⌃⇧M"],
  ["Open project picker", "Open the composer project picker", "⌥⇧⌘O"],
  ["Start dictation", "Start dictation in the current composer", "⌃⇧D"],
  ["Send message", "Send the current composer message", "Unassigned"],
  [
    "Toggle Fast mode",
    "Turn Fast mode on or off in the current composer",
    "Unassigned",
  ],
  [
    "Toggle plan mode",
    "Turn plan mode on or off in the current composer",
    "Unassigned",
  ],
  [
    "Toggle Cloud/Local",
    "Switch ChatGPT Work between cloud and local execution",
    "Unassigned",
  ],
  [
    "Toggle Local/Worktree",
    "Switch the current composer between local and a new worktree",
    "Unassigned",
  ],
  ["Copy as Markdown", "Copy the current chat as Markdown", "Unassigned"],
  ["Copy conversation path", "Copy the current chat path", "⌥⇧⌘C"],
  ["Copy deeplink", "Copy a deeplink to the current chat", "⌥⌘L"],
  ["Copy session id", "Copy the current chat session ID", "⌥⌘C"],
  ["Copy working directory", "Copy the current chat working directory", "⇧⌘C"],
  [
    "Continue in new chat",
    "Create a new chat from the current chat",
    "Unassigned",
  ],
  ["Force Reload Browser Page", "Force reload the active browser page", "⇧⌘R"],
  ["Browser back", "Go back in browser history", "⌘Left"],
  ["Browser forward", "Go forward in browser history", "⌘Right"],
  ["New Window", "Open a new window", "Unassigned"],
  ["Open command menu", "Open the command menu", "⌘K", "⇧⌘P"],
  ["Reload Browser Page", "Reload the active browser page", "⌘R"],
  ["Rename chat", "Rename the current chat", "⌥⌘R"],
  ["Search Files…", "Search files", "⌘P"],
  ["Show keyboard shortcuts", "Show the shortcuts available right now", "⌘/"],
  ["Go to chat 1", "Open the visible chat in this shortcut slot", "⌘1"],
  ["Go to chat 2", "Open the visible chat in this shortcut slot", "⌘2"],
  ["Go to chat 3", "Open the visible chat in this shortcut slot", "⌘3"],
  ["Go to chat 4", "Open the visible chat in this shortcut slot", "⌘4"],
  ["Go to chat 5", "Open the visible chat in this shortcut slot", "⌘5"],
  ["Go to chat 6", "Open the visible chat in this shortcut slot", "⌘6"],
  ["Go to chat 7", "Open the visible chat in this shortcut slot", "⌘7"],
  ["Go to chat 8", "Open the visible chat in this shortcut slot", "⌘8"],
  ["Go to chat 9", "Open the visible chat in this shortcut slot", "⌘9"],
  ["Toggle File Tree", "Toggle the file tree panel", "⇧⌘E"],
  [
    "Toggle maximize side panel",
    "Expand or restore the side panel",
    "Unassigned",
  ],
  ["Start Trace Recording", "Start or stop trace recording", "⇧⌘S"],
];
